import { DEFAULT_SETTINGS } from "@/lib/flipbook-rules";
import type { Flipbook, TextRun } from "@/lib/types";

// Demo workspace seeded for the demo user: the dashboard rows from the design handoff
// plus six older books, so the sidebar count (12) matches the design.

const now = Date.now();
const minutesAgo = (m: number) => new Date(now - m * 60_000).toISOString();
const hoursAgo = (h: number) => minutesAgo(h * 60);

type MockFlipbook = Omit<Flipbook, "userId" | "settings" | "createdAt" | "thumbnailUrl"> & {
  cover?: { runs: TextRun[]; caption: string };
};

// The first six rows mirror the dashboard in the design handoff, in the same order.
const rows: MockFlipbook[] = [
  {
    id: "fb_8Kd2",
    title: "Summer Catalog 2026",
    slug: "summer-catalog",
    type: "PDF",
    status: "PUBLISHED",
    visibility: "PUBLIC",
    description: "Sixty-four pages of the new season, photographed in Lisbon. Shop the full summer range.",
    pageCount: 64,
    fileSize: 18.4e6,
    error: null,
    thumbnailTint: ["#E8DFC9", "#D2C4A4"],
    views: 12_480,
    updatedAt: hoursAgo(2),
    publishedAt: "2026-08-21T10:00:00.000Z",
    cover: {
      runs: [{ text: "Summer\n" }, { text: "Catalog", italic: true }, { text: " 26" }],
      caption: "Sixty-four pages of the new season, photographed in Lisbon.",
    },
  },
  {
    id: "fb_3Qx7",
    title: "Brand Guidelines v4",
    slug: "brand-guidelines-v4",
    type: "CANVAS",
    status: "PUBLISHED",
    visibility: "PUBLIC",
    description: "Logo, colour, type and voice. Everything the team needs to keep the brand consistent.",
    pageCount: 28,
    fileSize: null,
    error: null,
    thumbnailTint: ["#DCE3FA", "#BCC8F2"],
    views: 3_106,
    updatedAt: hoursAgo(26),
    publishedAt: "2026-07-02T09:00:00.000Z",
    cover: {
      runs: [{ text: "Brand\n" }, { text: "Guidelines", italic: true }],
      caption: "Version four. Logo, colour, type and voice.",
    },
  },
  {
    id: "fb_5Tn1",
    title: "Annual Report 2026",
    slug: "annual-report-2026",
    type: "PDF",
    status: "PROCESSING",
    visibility: "PUBLIC",
    description: "Results, highlights and outlook for the 2026 financial year.",
    pageCount: 64,
    fileSize: 31.2e6,
    error: null,
    thumbnailTint: ["#EFEBE2", "#DDD7C9"],
    views: null,
    updatedAt: minutesAgo(0),
    publishedAt: null,
  },
  {
    id: "fb_9Rw4",
    title: "Lookbook SS26",
    slug: "lookbook-ss26",
    type: "PDF",
    status: "READY",
    visibility: "PUBLIC",
    description: "Spring/Summer 2026 lookbook. Forty-two pages of the new collection.",
    pageCount: 42,
    fileSize: 22.1e6,
    error: null,
    thumbnailTint: ["#F2DFD9", "#E0C3B8"],
    views: 0,
    updatedAt: minutesAgo(2),
    publishedAt: null,
  },
  {
    id: "fb_2Hc6",
    title: "Investor Deck",
    slug: "investor-deck",
    type: "CANVAS",
    status: "DRAFT",
    visibility: "PRIVATE",
    description: "Seed round overview for prospective investors.",
    pageCount: 16,
    fileSize: null,
    error: null,
    thumbnailTint: ["#E2EDE6", "#C7DCD0"],
    views: null,
    updatedAt: "2026-09-04T15:20:00.000Z",
    publishedAt: null,
  },
  {
    id: "fb_7Pm3",
    title: "Pricing v3",
    slug: "pricing-v3",
    type: "PDF",
    status: "FAILED",
    visibility: "PUBLIC",
    description: "Price list for the 2026 season.",
    pageCount: 0,
    fileSize: 2.3e6,
    error: "invalid font",
    thumbnailTint: ["#F3EFEA", "#E3DDD3"],
    views: null,
    updatedAt: "2026-09-02T11:05:00.000Z",
    publishedAt: null,
  },
  {
    id: "fb_4Mn8",
    title: "Spring Menu 2026",
    slug: "spring-menu-2026",
    type: "PDF",
    status: "PUBLISHED",
    visibility: "PUBLIC",
    description: "Seasonal menu for the spring terrace.",
    pageCount: 12,
    fileSize: 4.2e6,
    error: null,
    thumbnailTint: ["#F6F1E4", "#E6DCC2"],
    views: 9_812,
    updatedAt: "2026-08-30T08:40:00.000Z",
    publishedAt: "2026-08-30T08:40:00.000Z",
  },
  {
    id: "fb_6Jd1",
    title: "Onboarding Guide",
    slug: "onboarding-guide",
    type: "CANVAS",
    status: "PUBLISHED",
    visibility: "PUBLIC",
    description: "Your first week at the studio, page by page.",
    pageCount: 20,
    fileSize: null,
    error: null,
    thumbnailTint: ["#EAF0F3", "#CBD9E0"],
    views: 6_240,
    updatedAt: "2026-08-27T14:00:00.000Z",
    publishedAt: "2026-08-27T14:00:00.000Z",
  },
  {
    id: "fb_1Cs5",
    title: "Case Studies 2026",
    slug: "case-studies-2026",
    type: "PDF",
    status: "PUBLISHED",
    visibility: "PUBLIC",
    description: "Six client projects, from brief to launch.",
    pageCount: 36,
    fileSize: 14.9e6,
    error: null,
    thumbnailTint: ["#EFF3EF", "#CFDCD3"],
    views: 5_318,
    updatedAt: "2026-08-18T16:30:00.000Z",
    publishedAt: "2026-08-18T16:30:00.000Z",
  },
  {
    id: "fb_8Wc3",
    title: "Winter Catalog 2025",
    slug: "winter-catalog-2025",
    type: "PDF",
    status: "PUBLISHED",
    visibility: "PUBLIC",
    description: "The 2025 winter range in fifty-six pages.",
    pageCount: 56,
    fileSize: 21.7e6,
    error: null,
    thumbnailTint: ["#E4E9F2", "#C4CCDD"],
    views: 8_904,
    updatedAt: "2026-07-30T10:10:00.000Z",
    publishedAt: "2025-11-04T10:10:00.000Z",
  },
  {
    id: "fb_3Ev7",
    title: "Event Programme",
    slug: "event-programme",
    type: "PDF",
    status: "PUBLISHED",
    visibility: "PUBLIC",
    description: "Talks, workshops and times for the summer event.",
    pageCount: 24,
    fileSize: 6.8e6,
    error: null,
    thumbnailTint: ["#F5E9E4", "#E3CBC0"],
    views: 1_970,
    updatedAt: "2026-07-12T09:00:00.000Z",
    publishedAt: "2026-07-12T09:00:00.000Z",
  },
  {
    id: "fb_5Pf2",
    title: "Portfolio 2025",
    slug: "portfolio-2025",
    type: "CANVAS",
    status: "PUBLISHED",
    visibility: "UNLISTED",
    description: "Selected work from 2025.",
    pageCount: 18,
    fileSize: null,
    error: null,
    thumbnailTint: ["#F1EDF4", "#D8CEE0"],
    views: 360,
    updatedAt: "2026-06-20T12:00:00.000Z",
    publishedAt: "2026-06-20T12:00:00.000Z",
  },
];

export type DemoFlipbook = Omit<Flipbook, "userId"> & { cover?: MockFlipbook["cover"] };

export const demoFlipbooks: DemoFlipbook[] = rows.map((row) => ({
  ...row,
  settings: DEFAULT_SETTINGS,
  thumbnailUrl: null,
  createdAt: row.publishedAt ?? row.updatedAt,
}));
